FROM ruby:3.2.1-alpine

RUN apk update && apk add --update --no-cache build-base tzdata libpq git yarn npm

WORKDIR /app

ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock

RUN gem install bundler
RUN bundle install --jobs 20 --retry 5

